# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: author

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - bender9507
  - HyunseoY
  - wsdx123
  - jeonhaekang

numberOfReviewers: 3
